#TUPLAS 
#CREAR Y MOSTRAR TUPLAS
a=()
print (a)
a=("Hello","hola","Hallo")
print(a)
#MOSTRAR UN ELEMENTO DE LA TUPLA
print(a[1])

#MODIFICAR ELEMENTOS DE UNA TUPLA
#a[0]="Bounjour" UNA TUPLA UNA VEZ DECLARADA ES INMODIFICABLE

#FUNCIONES
print(a.count("Hallo"))#CONTAR CUANTAS VECES SE REPITE EL ELEMENTO
print(len(a))#CONTAR CUÁNTOS ELEMENTOS TIENE LA TUPLA
print(a.index("hola"))#REGRESA LA POSICIÓN DEL ELEMENTO QUE PASAMOS COMO PARÁMETRO